# Generated by Django 5.1.2 on 2024-10-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sold',
            name='sent',
            field=models.CharField(choices=[('B', 'Back to Store'), ('F', 'Package Wait for send'), ('T', 'Package sent')], default='F', help_text='Is package sent?', max_length=1, verbose_name='Send Status'),
        ),
    ]
