# Generated by Django 5.1.2 on 2024-10-27 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_post_options_comments_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinstance',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
    ]
