# Generated by Django 5.1.2 on 2024-10-27 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_productinstance_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselbanner',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select a category for the carousel banner', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carousel_banners', to='shop.productcategory'),
        ),
        migrations.AlterField(
            model_name='sold',
            name='sent',
            field=models.CharField(choices=[('F', 'Package Wait for send'), ('B', 'Back to Store'), ('T', 'Package sent')], default='F', help_text='Is package sent?', max_length=1, verbose_name='Send Status'),
        ),
    ]
