# Generated by Django 5.1.2 on 2024-10-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_carouselbanner_category_alter_sold_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hex_code',
            field=models.CharField(default=1, help_text='Enter a hex code for the color', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sold',
            name='sent',
            field=models.CharField(choices=[('F', 'Package Wait for send'), ('T', 'Package sent'), ('B', 'Back to Store')], default='F', help_text='Is package sent?', max_length=1, verbose_name='Send Status'),
        ),
    ]
